backend:
  name: git-gateway
  branch: main

media_folder: "assets/stories"
public_folder: "/assets/stories"

editor:
  preview: false
  tinymce:
    apiKey: "tlxgh1hiy34s3h2mx3idq6nfpc0hqdkjq3xolge00dz6x1xq"

collections:
  - name: "stories"
    label: "Povídky"
    folder: "data/stories"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"

    fields:
      - label: "ID"
  name: "id"
  widget: "hidden"
  default: "{{slug}}"

      - label: "Název"
        name: "title"
        widget: "string"

      - label: "Anotace"
        name: "annotation"
        widget: "text"

      - label: "Meta"
        name: "meta"
        widget: "string"
        required: false

      - label: "Obrázek"
        name: "image"
        widget: "image"
        required: false

      - label: "Text povídky"
        name: "content"
        widget: "rich-text"
